In [1]:
!pip install scikit-learn


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import sklearn.preprocessing as pp
import numpy as np 

x = np.array([
    [1,15000,100000],
    [20,80,900000],
    [1.5696,6,5]
])

x_scale = pp.scale(x)
x_scale

array([[-0.73913144,  1.41420058, -0.57933024],
       [ 1.41372257, -0.70185271,  1.40693069],
       [-0.67459114, -0.71234788, -0.82760045]])

In [11]:
min_max_scaler = pp.MinMaxScaler()
x_minmax = min_max_scaler.fit_transform(x)
x_minmax

array([[0.        , 1.        , 0.11110617],
       [1.        , 0.00493531, 1.        ],
       [0.02997895, 0.        , 0.        ]])

In [12]:
# normalization
x = [[80,60,20]]
pp.normalize(x, norm='max')

array([[1.  , 0.75, 0.25]])

In [13]:
# categorical encoding 
# ordinal encoding 
x = [['yes'], ['no']]
enc = pp.OrdinalEncoder()
enc.fit_transform(x)


array([[1.],
       [0.]])

In [14]:
# lable encoding
import pandas as pd 
data = pd.read_csv('./IRIS.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [15]:
data.species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
enc = pp.LabelEncoder()
data.species = enc.fit_transform(data.species)
data.head()
data.species.unique()


array([0, 1, 2], dtype=int64)